# Generated by Django 3.1.3 on 2020-11-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0005_auto_20201122_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='avatar',
            field=models.ImageField(blank=True, default='cuenta/default.jpg', null=True, upload_to='cuenta/'),
        ),
    ]
