# Generated by Django 3.1.3 on 2020-11-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0007_auto_20201122_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='detalle',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
