# Generated by Django 3.1.3 on 2020-11-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0008_auto_20201125_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado',
            new_name='completado',
        ),
    ]
